# Generated by Django 3.0.5 on 2020-05-31 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20200531_0713'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='full_decription',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
