# Generated by Django 3.0.5 on 2020-06-03 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20200602_2016'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Userprofile',
        ),
    ]
