# Generated by Django 3.0.5 on 2020-06-06 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20200603_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='revenue',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
