# Generated by Django 3.0.5 on 2020-06-08 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_auto_20200608_0814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='notif',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='referrals',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='subcription',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='tasks_completed',
            field=models.IntegerField(null=True),
        ),
    ]
