# Generated by Django 3.0.5 on 2020-06-08 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_auto_20200608_0832'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='sub',
            field=models.CharField(choices=[('personal', 'Personal'), ('none', 'none')], default=0, max_length=10),
            preserve_default=False,
        ),
    ]
