# Generated by Django 3.0.5 on 2020-06-08 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_userprofile_sub'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='sub1',
            field=models.CharField(choices=[('Business', 'Business'), ('..', '..')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='sub2',
            field=models.CharField(choices=[('Ultimate', 'Ultimate'), ('..', '..')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='sub3',
            field=models.CharField(choices=[('Premium', 'Premium'), ('..', '..')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='revenue',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='sub',
            field=models.CharField(choices=[('Personal', 'Personal'), ('..', '..')], max_length=10, null=True),
        ),
    ]
