# Generated by Django 3.0.5 on 2020-06-08 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_auto_20200608_0953'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='sub1',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='sub2',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='sub3',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='sub',
            field=models.CharField(choices=[('Personal', 'Personal'), ('..', '..')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
