# Generated by Django 3.0.5 on 2020-06-08 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_auto_20200608_1051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='sub',
        ),
    ]
