# Generated by Django 3.0.5 on 2020-06-08 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_remove_userprofile_sub'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='sub',
            field=models.CharField(choices=[('Personal', 'Personal'), ('..', '..')], default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='revenue',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
