# Generated by Django 3.0.5 on 2020-06-08 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0020_auto_20200608_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='sub1',
            field=models.CharField(choices=[('Business', 'Business'), ('..', '..')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='sub2',
            field=models.CharField(choices=[('Ultimate', 'Ultimate'), ('..', '..')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='sub3',
            field=models.CharField(choices=[('Premium', 'Premium'), ('..', '..')], max_length=10, null=True),
        ),
    ]
