# Generated by Django 3.0.5 on 2020-06-08 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0023_personal_good'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personal',
            name='good',
        ),
    ]
