# Generated by Django 3.0.5 on 2020-06-08 16:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0025_auto_20200608_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsored',
            name='shared',
            field=models.ManyToManyField(blank=True, default=None, related_name='shared', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sponsored',
            name='title',
            field=models.CharField(default=0, max_length=150),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Share',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('values', models.CharField(choices=[('Earn', 'Earn'), ('Forfeit', 'Forfeit')], default='Earn', max_length=10)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Sponsored')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
