# Generated by Django 3.0.5 on 2020-06-08 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0027_auto_20200608_2218'),
    ]

    operations = [
        migrations.AddField(
            model_name='share',
            name='count',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
