# Generated by Django 3.0.5 on 2020-06-09 06:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0028_share_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sponsored',
            name='shared',
        ),
        migrations.AddField(
            model_name='sponsored',
            name='shared',
            field=models.OneToOneField(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='shared', to=settings.AUTH_USER_MODEL),
        ),
    ]
