# Generated by Django 3.0.5 on 2020-06-09 06:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0029_auto_20200609_0739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsored',
            name='shared',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='shared', to=settings.AUTH_USER_MODEL),
        ),
    ]
