# Generated by Django 3.0.5 on 2020-06-09 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0032_auto_20200609_0743'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sponsored',
            name='shared',
        ),
    ]
