# Generated by Django 3.0.5 on 2020-06-09 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0034_sponsored_shared'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sponsored',
            name='shared',
        ),
    ]
