# Generated by Django 3.0.5 on 2020-06-09 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0038_auto_20200609_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='share',
            name='count',
            field=models.IntegerField(choices=[('1', '1'), ('0', '0')], default='1', max_length=10),
        ),
    ]
