# Generated by Django 3.0.5 on 2020-06-09 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0040_remove_share_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='share',
            name='count',
            field=models.IntegerField(null=True),
        ),
    ]
